# server.port=8080

# spring.application.name=api-gateway
# spring.cloud.gateway.routes[0].id=user-service
# spring.cloud.gateway.routes[0].uri=http://user-service:8080
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
# spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/users/(?<segment>.*), /${segment}

# # spring.cloud.gateway.routes[0].id=otp-service
# # spring.cloud.gateway.routes[0].uri=http://otp-service:8080
# # spring.cloud.gateway.routes[0].predicates[0]=Path=/api/otp/**


# spring.cloud.gateway.routes[1].id=otp-service
# spring.cloud.gateway.routes[1].uri=http://otp-service:8080
# spring.cloud.gateway.routes[1].predicates[0]=Path=/api/otp/**
# # api-gateway/src/main/resources/application.properties
# spring.cloud.gateway.routes[1].filters[1]=RewritePath=/api/otp/(?<segment>.*), /${segment}



server.port=8080

spring.application.name=api-gateway

# User-Service Route (works) (remove from uri -> :80 to work in kind)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://user-service:${USER_SERVICE_PORT:80}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/users/(?<segment>.*),/$\{segment}

# OTP-Service Route (fix this)
spring.cloud.gateway.routes[1].id=otp-service
spring.cloud.gateway.routes[1].uri=http://otp-service:${OTP_SERVICE_PORT:80}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/otp/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/otp/(?<segment>.*),/$\{segment}


# Payment-Service Route
spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=http://payment-service:${PAYMENT_SERVICE_PORT:80}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/payments/(?<segment>.*),/$\{segment}

# train service
spring.cloud.gateway.routes[3].id=train-service
spring.cloud.gateway.routes[3].uri=http://train-service:${TRAIN_SERVICE_PORT:80}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/train-service/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/train-service/(?<segment>.*),/$\{segment}


# coach service
spring.cloud.gateway.routes[4].id=coach-seat-service
spring.cloud.gateway.routes[4].uri=http://coach-seat-service:${COACH_SEAT_SERVICE_PORT:80}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/coach-seat-service/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/api/coach-seat-service/(?<segment>.*),/$\{segment}