apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: railway-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: heisamit/payment-service:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:payment_db"
        - name: SPRING_PROFILES_ACTIVE
          value: "mock"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: railway-system
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080