spring.application.name=otp-service
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:otp_db
spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Mail (configure with your SMTP details)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sahaamit20002@gmail.com
spring.mail.password=mryb srze cddf jrsm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


